services:
  - type: web
    name: stopanarque
    runtime: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push --skip-generate && npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SITE_URL
        value: https://stopanarque.bj
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: file:/var/data/stopanarque.db
    disk:
      name: stopanarque-data
      mountPath: /var/data
      sizeGB: 1
